```python
import math
import os

import cadquery as cq
from cadquery import exporters

COMPONENT_NAME = "belt_tensioner_bracket_corexy"

BASE_PLATE_LENGTH = 80.0
BASE_PLATE_WIDTH = 50.0
BASE_PLATE_THICKNESS = 3.0

VERTICAL_TAB_HEIGHT = 40.0
VERTICAL_TAB_THICKNESS = 3.0

M5_HOLE_DIAMETER = 5.5
N_M5_HOLES = 2
M5_HOLE_SPACING_Y = 40.0
M5_HOLE_OFFSET_X = 12.5

M4_SLOT_LENGTH = 20.0
M4_SLOT_WIDTH = 6.0
M4_SLOT_CENTER_Y = 10.0

MIN_WALL_THICKNESS = 2.0
FILLET_RADIUS = 1.5

GUSSET_THICKNESS = 3.0
GUSSET_BASE_LENGTH = 15.0
GUSSET_HEIGHT = 20.0
GUSSET_ANGLE_DEG = 45.0

M5_HOLE_Y1 = M5_HOLE_SPACING_Y / 2.0
M5_HOLE_Y2 = -M5_HOLE_SPACING_Y / 2.0
M5_HOLE_X_LEFT = -M5_HOLE_OFFSET_X
M5_HOLE_X_RIGHT = M5_HOLE_OFFSET_X

GUSSET_BASE_X_LEFT = -BASE_PLATE_WIDTH / 2.0
GUSSET_BASE_X_RIGHT = BASE_PLATE_WIDTH / 2.0
GUSSET_BASE_Y = -BASE_PLATE_LENGTH / 2.0
GUSSET_BASE_Z = BASE_PLATE_THICKNESS

GE
