---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	design_synthesis_agent(design_synthesis_agent)
	geometry_planner_agent(geometry_planner_agent)
	critic_checkpoint_a(critic_checkpoint_a)
	parameter_agent(parameter_agent)
	code_generation_infill_agent(code_generation_infill_agent)
	execution_validation_node(execution_validation_node)
	contract_validation_node(contract_validation_node)
	repair_agent(repair_agent)
	critic_checkpoint_b(critic_checkpoint_b)
	export_summary_agent(export_summary_agent)
	__end__([<p>__end__</p>]):::last
	__start__ --> design_synthesis_agent;
	code_generation_infill_agent --> execution_validation_node;
	contract_validation_node -.-> critic_checkpoint_b;
	contract_validation_node -.-> export_summary_agent;
	critic_checkpoint_a -.-> geometry_planner_agent;
	critic_checkpoint_a -.-> parameter_agent;
	critic_checkpoint_b -.-> code_generation_infill_agent;
	critic_checkpoint_b -.-> export_summary_agent;
	critic_checkpoint_b -.-> geometry_planner_agent;
	design_synthesis_agent -.-> code_generation_infill_agent;
	design_synthesis_agent -.-> geometry_planner_agent;
	execution_validation_node -.-> code_generation_infill_agent;
	execution_validation_node -.-> contract_validation_node;
	execution_validation_node -.-> repair_agent;
	geometry_planner_agent --> critic_checkpoint_a;
	parameter_agent --> code_generation_infill_agent;
	repair_agent -.-> code_generation_infill_agent;
	repair_agent -.-> contract_validation_node;
	repair_agent -.-> execution_validation_node;
	repair_agent -.-> geometry_planner_agent;
	export_summary_agent --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
